sudo: false

language: erlang

before_install:
  - pip install --user cpp-coveralls coveralls-merge

install:
  - rebar -C rebar.test.config get-deps

script: rebar -C rebar.test.config compile xref && rebar -C rebar.test.config eunit skip_deps=true

otp_release:
  - 17.1
  - 17.5
  - 18.1

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json
